# -*- coding: utf-8 -*-
"""playStore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YAODVqGlsBrrzD7hvIcuhCQdkm6JojPX
"""

import pandas as pd

df=pd.read_csv("/content/googleplaystore[1].csv")

df

df.head()

df.tail()

df.info()

df.describe()

df.shape[1]

df.isnull().sum()

df.columns

df[df["App"].str.contains("ASTROLOGY",case=False)]

df['Rating'].mean()

df.columns

df['Category'].nunique()

df.value_counts('Category')

df.groupby('Category')['Rating'].mean().sort_values(ascending=True).head()

len(df[df['Rating']==5.0])

sum(df['Rating']==5.0)

df["Reviews"].dtypes

df.isnull().sum()

df["Reviews"]=df["Reviews"].replace({"3.0M":"3.0"})

df["Reviews"]=df["Reviews"].astype("float")

df["Reviews"].dtype

df["Reviews"].mean()

a=df["Type"].value_counts()

df["Type"].value_counts()

df.columns

df[df['Reviews']==df['Reviews'].max()]["App"]

index=df['Reviews'].sort_values(ascending=False).head(3).index

df.iloc[index]["App"]

df.groupby("Type")['Rating'].mean()

df["Installsy"]=df["Installs"].str.replace("+","",regex=False)



df["Installsy"] = df["Installs"].str.replace(r'[+,]', '', regex=True).str.replace(r'(?i)free', '0', regex=True)

df["Installsy"]

df["Installsy"]=df["Installsy"].astype("int")

i=df["Installsy"].sort_values(ascending=False).head(5).index

df["App"].iloc[i]